### ISSUE TITLE
 404 Error

### ISSUE THREAD

**Issue by grotego** [SplashSync/Magento1#1]
Magento version 1.9.3.6

I follow the steps until i access : System >> Configuration then Services >> Splash Sync Connector.
Then i get a 404 page not found error.

**Comment by BadPixxel** [comment]
Hi,

Could you please enable debug mode to see more details on this error?
Did  you download the module from our site or raw sources from Github? You may have to compile the module (" php composer update --no-dev")

BR

**Comment by BadPixxel** [comment]
Hi Grotego,

We performed deeper tests and it appears this is not a bug, you just need to logout and login again in order to update ACL permissions. 

We added a not on documentation: [https://github.com/SplashSync/Magento1/wiki/Configuration](https://github.com/SplashSync/Magento1/wiki/Configuration)
Can you confirm it worked on your side?

Best regards,
